<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <Authors>7Bpencil</Authors>
    <Copyright>Copyright (c) 7Bpencil 2026</Copyright>
    <AssemblyName>7Bpencil.BECheats</AssemblyName>
    <AssemblyVersion>0.0.1</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SPTPath>..\..\Escape from Tarkov</SPTPath>
    <OutPath>$(SPTPath)\BepInEx\plugins\7Bpencil.BECheats</OutPath>
    <StagePath>.\Stage\BepInEx\plugins\7Bpencil.BECheats</StagePath>
    <AssemblySearchPaths>
      $(AssemblySearchPaths);
      $(SPTPath)\BepInEx\core;
      $(SPTPath)\BepInEx\interop;
      $(SPTPath)\BepInEx\unity-libs;
      $(SPTPath)\BepInEx\plugins\sptushonka;
    </AssemblySearchPaths>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx.Core" />
    <Reference Include="BepInEx.Unity.IL2CPP" />
    <Reference Include="Comfort" />
    <Reference Include="Il2Cppmscorlib" />
    <Reference Include="Il2CppInterop.Runtime" />
    <Reference Include="SPTushonka.Reflection" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.CoreModule" />
  </ItemGroup>

  <Target Name="CopyToSPT" AfterTargets="AfterBuild">
    <Exec Command="mkdir &quot;$(OutPath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutPath)" />
  </Target>

  <Target Name="CopyToStage" AfterTargets="AfterBuild" Condition="'$(Configuration)'=='Release'">
    <Exec Command="mkdir &quot;$(StagePath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StagePath)" />
  </Target>

</Project>
