<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>7Bpencil</Authors>
    <Copyright>Copyright (c) 7Bpencil 2026</Copyright>
    <AssemblyName>7Bpencil.BECheats.Server</AssemblyName>
    <AssemblyVersion>0.0.1</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SPTPath>..\..\..\Escape from Tarkov</SPTPath>
    <OutPath>$(SPTPath)\SPT_Runtime\user\mods\7Bpencil.BECheats.Server</OutPath>
    <StagePath>..\Stage\SPT_Runtime\user\mods\7Bpencil.BECheats.Server</StagePath>
    <AssemblySearchPaths>
      $(AssemblySearchPaths);
      $(SPTPath)\SPT_Runtime;
    </AssemblySearchPaths>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.Common" />
    <Reference Include="SPTarkov.DI" />
    <Reference Include="SPTarkov.Server.Core" />
    <Reference Include="SemanticVersioning" />
    <Reference Include="Spectre.Console" />
    <Reference Include="Spectre.Console.Ansi" />
  </ItemGroup>

  <Target Name="CopyToSPT" AfterTargets="AfterBuild">
    <Exec Command="mkdir &quot;$(OutPath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutPath)" />
  </Target>

  <Target Name="CopyToStage" AfterTargets="AfterBuild" Condition="'$(Configuration)'=='Release'">
    <Exec Command="mkdir &quot;$(StagePath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StagePath)" />
  </Target>

</Project>
